dozzle:
  image: amir20/dozzle:latest
  container_name: dozzle
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.dozzle.rule=Host(`api-homelab.jeerasakananta.dev`) && PathPrefix(`/logs`)"
    - "traefik.http.routers.dozzle.entrypoints=websecure"
    - "traefik.http.routers.dozzle.tls.certresolver=cloudflare"
    - "traefik.http.middlewares.logs-strip.stripprefix.prefixes=/logs"
    - "traefik.http.routers.dozzle.middlewares=logs-strip"

  networks:
    - homelab
