services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    command: server /data --console-address ":9001"
    restart: always
networks: {}
