---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- New:
    - Glance:
            icon: si-glance
            href: https://rss.jeerasakananta.dev
            description: rss feed reader
    

- Infrastructure:
    - Cockpit:
        icon: si-cockpit
        href: https://cockpit.jeerasakananta.dev
        description: Server administration interface

    - Dockge:
        icon: dockge
        href: https://dockge.jeerasakananta.dev/
        description: dockge

    - Proxmox VE:
        icon: proxmox.png
        href: https://proxmox.jeerasakananta.dev
        description: Virtualization management platform

- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma.jeerasakananta.dev
        description: Service uptime monitoring
        server: my-docker
        container: uptime-kuma
           
    - Netdata:
        icon: netdata.png
        href: https://netdata.jeerasakananta.dev
        description: Real-time performance monitoring
        server: my-docker
        container: netdata

    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.jeerasakananta.dev/logs
        description: Docker logs viewer

- Services:
    - N8N:
        icon: n8n.png
        href: http://n8n.jeerasakananta.dev
        description: Workflow automation tools

    - OpenWebUI:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/open-webui.webp
        href: https://webui.jeerasakananta.dev
        description: Open WebUI for LLMs

- Storage & Backup:
    - MinIO:
        icon: minio
        href: https://minio.jeerasakananta.dev
        description: Object Storage (S3 Compatible)
        server: my-docker
        container: minio
    
    - pgadmin:
        icon: pgadmin.png
        href: https://pgadmin.jeerasakananta.dev
        description: PostgreSQL database management
        server: my-docker
        container: pgadmin4
    
- Dev / Data:
    - VS Code:
        icon: si-visualstudiocode
        href: https://code.jeerasakananta.dev
        description: Browser-based IDE
        server: my-docker
        container: vscode-server

    - JupyterLab:
        icon: si-jupyter
        href: http://jupyterlab.jeerasakananta.dev
        description: Data science and machine learning environment
        server: my-docker
        container: jupyterlab

- Docs & Wiki:
    - BookStack:
        icon: bookstack.png
        href: https://wiki.jeerasakananta.dev
        description: Documentation and wiki platform
        server: my-docker
        container: bookstack

- Auth & Security:
    - Keycloak:
        icon: keycloak.png
        href: https://keycloak.jeerasakananta.dev
        description: Identity and access management
        server: my-docker
        container: keycloak

    - Authelia:
        icon: authelia.png
        href: https://auth.jeerasakananta.dev
        description: Authentication and authorization server
        server: my-docker
        container: authelia