---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - Cockpit:
        icon: si-cockpit
        href: https://cockpit.jeerasakananta.dev
        description: Server administration interface
    
    - Coolify:
        icon: coolify.png
        href: https://coolify.jeerasakananta.dev
        description: Self-hosted PaaS platform
        server: my-docker
        container: coolify

    - Portainer:
        icon: portainer.png
        href: https://portainer.jeerasakananta.dev
        description: Container management platform
        server: my-docker
        container: portainer
    
    - Proxmox VE:
        icon: proxmox.png
        href: https://proxmox.jeerasakananta.dev
        description: Virtualization management platform

- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma.jeerasakananta.dev
        description: Service uptime monitoring
        server: my-docker
        container: uptime-kuma
        
    - Grafana:
        icon: grafana.png
        href: https://grafana.jeerasakananta.dev
        description: Analytics and visualization
        server: my-docker
        container: grafana
    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.jeerasakananta.dev
        description: Monitoring and alerting toolkit
        server: my-docker
        container: prometheus
    - Loki:
        icon: loki.png
        href: https://loki.jeerasakananta.dev
        description: Log aggregation system
        server: my-docker
        container: loki
        
    - Netdata:
        icon: netdata.png
        href: http://10.50.5.51:19999
        description: Real-time performance monitoring
        server: my-docker
        container: netdata

- Services:     
    - Glance:
        icon: si-glance
        href: https://glance.jeerasakananta.dev
        description: rss feed reader
    
    - N8N:
        icon: n8n.png
        href: http://n8n.jeerasakananta.dev
        description: Workflow automation tools
    
    - pgadmin:
        icon: pgadmin.png
        href: https://pgadmin.jeerasakananta.dev
        description: PostgreSQL database management
        server: my-docker
        container: pgadmin4
     
    - Dozzle:
        icon: dozzle.png
        href: https://api-homelab.jeerasakananta.dev/logs
        description: Docker logs viewer

- Storage & Backup:
    - Nextcloud:
        icon: nextcloud.png
        href: https://cloud.jeerasakananta.dev
        description: File sync and sharing platform
        server: my-docker
        container: nextcloud

    - Duplicati:
        icon: duplicati.png
        href: https://backup.jeerasakananta.dev
        description: Backup solution
        server: my-docker
        container: duplicati

- Dev / Data:
    - jupyterlab:
        icon: si-jupyter
        href: http://jupyterlab.jeerasakananta.dev
        description: Data science and machine learning environment
        server: my-docker
        container: jupyterlab
    - dbber

- Docs & Wiki:
    - BookStack:
        icon: bookstack.png
        href: https://wiki.jeerasakananta.dev
        description: Documentation and wiki platform
        server: my-docker
        container: bookstack



- Auth & Security:
    - Keycloak:
        icon: keycloak.png
        href: https://keycloak.jeerasakananta.dev
        description: Identity and access management
        server: my-docker
        container: keycloak

    - Authelia:
        icon: authelia.png
        href: https://auth.jeerasakananta.dev
        description: Authentication and authorization server
        server: my-docker
        container: authelia
    