---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homelab Dashboard
favicon: homepage.png

theme: dark
color: slate

layout:

  Services:
    style: row
    columns: 4
  
  Infrastructure:
    style: row
    columns: 4

  Monitoring:
    style: row
    columns: 4

  Storage & Backup:   
    style: row
    columns: 4

  Dev / Data:         
    style: row
    columns: 4

  Docs & Wiki:        
    style: row
    columns: 4

  Auth & Security:    
    style: row
    columns: 4

headerStyle: boxed
statusStyle: dot