services:
  dockge:
    image: louislam/dockge:nightly
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where to find your stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
networks: {}
